### ISSUE TITLE
Add interface for initial formulae

### ISSUE THREAD

**Issue by xbauch** [h0nzZik/libNTS_cpp#2]
Nts has a member _init, but there does not seem to be any way of declaring a formula to be initial.

**Comment by h0nzZik** [comment]
Something like:
```c++
Nts * nts = somehow_get_nts ();
std::unique_ptr < Formula > f = somehow_get_formula()
nts->init() = std::move ( f );
```
see [global variables](https://github.com/h0nzZik/llvm2nts/blob/master/llvm2nts/llvm2nts.cpp#L492-506). But maybe we could use list of formulas, implicitly connected with and, instead?

**Comment by xbauch** [comment]
Sorry, did not realise init() returns a non-const reference. I think that this solutions is perfectly acceptable. Closing this issue.
